version: '1'
services:
  - type: web
    name: flowchart-automation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
